import "./global.css";
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";

import "antd/dist/reset.css"; // ✅ Add this line to include Ant Design styles
import "./global.css";

import { Metadata } from "next";
import {
	Inter,
	Raleway,
	Roboto,
	Poppins,
	Nunito,
	Montserrat,
	Lato,
} from "next/font/google";
import Navbar from "../components/nav/Navbar";
import { Providers } from "./Providers";

// Your fonts
const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ weight: "400", subsets: ["latin"] });
const roboto = Roboto({ weight: "400", subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Brain Hustle",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`bg-background ${inter.className}`}>
					{/* Optional Clerk Auth Buttons */}
					{/* <header className="flex justify-end items-center p-4 gap-4 h-16">
						<SignedOut>
							<SignInButton />
							<SignUpButton />
						</SignedOut>
						<SignedIn>
							<UserButton />
						</SignedIn>
					</header> */}

					<Navbar />
					<Providers>{children}</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
