import "./global.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { Raleway } from "next/font/google";
import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
import { Nunito } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Lato } from "next/font/google";
import Navbar from "../components/nav/Navbar";
import { Providers } from "./Providers";
const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ weight: "400", subsets: ["latin"] });
const raleway500 = Raleway({ weight: "500", subsets: ["latin"] });
const raleway600 = Raleway({ weight: "600", subsets: ["latin"] });
const raleway700 = Raleway({ weight: "700", subsets: ["latin"] });
const roboto = Roboto({ weight: "400", subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] }); // Specify weight as a string

const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`bg-background ${inter.className}`}>
				<Navbar />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
